update: github action

diff --git a/.github/workflows/secret-scan.yml b/.github/workflows/secret-scan.yml
--- a/.github/workflows/secret-scan.yml
+++ b/.github/workflows/secret-scan.yml
@@ -12,4 +12,4 @@ jobs:
         id: branch-name
         run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
       - name: Search MYSQL variables
-        run: git grep -E 'MYSQL_\w+\s*=' $(git diff --name-only --diff-filter=ACMRTUXB origin/${{ steps.branch-name.outputs.branch }}) || return false
+        run: git grep -E 'MYSQL_\w+\s*=' $(git diff --name-only --diff-filter=ACMRTUXB origin/${{ steps.branch-name.outputs.branch }}) || echo "not found"
